name: Unpack Recovery/Boot Image
on:
  push:
    branches:
    - 'main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unpacking Image
      run: |
        wget -q https://raw.githubusercontent.com/DroidDumps/phoenix_firmware_dumper/main/utils/unpackboot.sh
        # wget ${LINK} >/dev/null
        # bash unpackboot.sh *img unpacked
        git config --global user.email "raza231198@gmail.com"
        git config --global user.name "MD Raza"
        git add .
        git commit -m "Unpacked" >/dev/null
        git push origin HEAD:main
